// AnimatedMaterial3D.runtime.js — UV, flipbook and video contributor for Material 3D Core.
if (typeof THREE !== 'undefined' && !gdjs.__animatedMaterial3D) {
  gdjs.__animatedMaterial3D = (function () {
    var MAPS = ['map','normalMap','roughnessMap','metalnessMap','aoMap','emissiveMap'];
    function finite(v,d){v=Number(v);return Number.isFinite(v)?v:d;}
    function rootOf(o){if(!o||typeof o.get3DRendererObject!=='function')return null;try{return o.get3DRendererObject()||null;}catch(e){return null;}}
    function read(b){return{
      tilingX:finite(b._getTilingX(),1),tilingY:finite(b._getTilingY(),1),offsetX:finite(b._getOffsetX(),0),offsetY:finite(b._getOffsetY(),0),
      rotation:finite(b._getRotationAngle(),0),centerX:finite(b._getRotationCenterX(),.5),centerY:finite(b._getRotationCenterY(),.5),
      scroll:!!b._getEnableScroll(),speedX:finite(b._getScrollSpeedX(),0),speedY:finite(b._getScrollSpeedY(),0),rotSpeed:finite(b._getScrollRotationSpeed(),0),
      flipbook:!!b._getEnableFlipbook(),columns:Math.max(1,Math.floor(finite(b._getFlipbookColumns(),1))),rows:Math.max(1,Math.floor(finite(b._getFlipbookRows(),1))),
      fps:Math.max(.01,finite(b._getFlipbookFPS(),12)),loop:!!b._getFlipbookLoop(),frames:Math.max(0,Math.floor(finite(b._getFlipbookTotalFrames(),0))),
      anisotropicFiltering:b._getAnisotropicFiltering?String(b._getAnisotropicFiltering()):'16x',
      targetMode:b._getTargetMode?String(b._getTargetMode()):'All materials',
      materialIndex:b._getMaterialIndex?Number(b._getMaterialIndex()):0,
      materialName:b._getMaterialName?String(b._getMaterialName()):'',
      meshName:b._getMeshName?String(b._getMeshName()):''
    };}
    function matchesTarget(p,mat,ctx){if(!p)return true;var m=p.targetMode||'All materials';if(m==='All materials')return true;if(m==='First material')return ctx&&ctx.slot!==undefined?ctx.slot===0:true;if(m==='Material index'){var idx=Number(p.materialIndex||0);return ctx&&ctx.slot!==undefined?ctx.slot===idx:true;}if(m==='Material name'){var n=String(p.materialName||'');return mat&&mat.name===n;}if(m==='Mesh name'){var mn=String(p.meshName||'');return ctx&&ctx.mesh&&ctx.mesh.name===mn;}return true;}
    function hasCore(o,root){if(root&&root.__m3dHasCore)return true;if(o&&typeof o.hasBehavior==='function'){return o.hasBehavior('MaterialCore3D')||o.hasBehavior('MaterialMaster');}return false;}
    function stateOf(b){if(!b.__animatedMaterial3DState)b.__animatedMaterial3DState={root:null,params:null,contributor:null,textures:[],x:0,y:0,rotation:0,frame:0,timer:0,playing:true,finished:false,video:null,videoTexture:null,state:'Uninitialized',error:'',appliedGeneration:-1};return b.__animatedMaterial3DState;}
    function transform(s){var p=s.params,rx=p.tilingX,ry=p.tilingY,ox=p.offsetX+s.x,oy=p.offsetY+s.y;if(p.flipbook){var total=p.frames>0?Math.min(p.frames,p.columns*p.rows):p.columns*p.rows;var f=Math.min(s.frame,Math.max(0,total-1));rx/=p.columns;ry/=p.rows;ox+=(f%p.columns)/p.columns;oy+=1-1/p.rows-Math.floor(f/p.columns)/p.rows;}for(var i=0;i<s.textures.length;i++){var t=s.textures[i];if(t.repeat&&t.repeat.set)t.repeat.set(rx,ry);if(t.offset&&t.offset.set)t.offset.set(ox,oy);t.rotation=(p.rotation+s.rotation)*Math.PI/180;if(t.center&&t.center.set)t.center.set(p.centerX,p.centerY);}}
    function attach(s,mat,ctx){if(!mat)return;if(!matchesTarget(s.params,mat,ctx))return;if(ctx&&ctx.mesh&&gdjs.__materialController3D&&gdjs.__materialController3D.ensureIsolatedMaterial){mat=gdjs.__materialController3D.ensureIsolatedMaterial({mesh:ctx.mesh,slot:ctx.slot,material:mat},ctx.root);}if(!mat.__m3dAnimatedOriginalMaps)mat.__m3dAnimatedOriginalMaps={};for(var i=0;i<MAPS.length;i++){var k=MAPS[i],source=mat[k];if(!source)continue;if(!mat.__m3dAnimatedOriginalMaps[k])mat.__m3dAnimatedOriginalMaps[k]=source;var clone=gdjs.__materialController3D.acquireTextureClone(ctx.root,s,mat.__m3dAnimatedOriginalMaps[k]);if(clone){mat[k]=clone;if(s.textures.indexOf(clone)<0)s.textures.push(clone);}}if(s.videoTexture){mat.map=s.videoTexture;if(s.textures.indexOf(s.videoTexture)<0)s.textures.push(s.videoTexture);}transform(s);mat.needsUpdate=true;}
    function detach(s,mat,ctx){if(!mat||!mat.__m3dAnimatedOriginalMaps)return;if(!matchesTarget(s.params,mat,ctx))return;for(var i=0;i<MAPS.length;i++){var k=MAPS[i];if(mat.__m3dAnimatedOriginalMaps[k])mat[k]=mat.__m3dAnimatedOriginalMaps[k];}delete mat.__m3dAnimatedOriginalMaps;mat.needsUpdate=true;}
    function sync(b,o){var s=stateOf(b),root=rootOf(o);if(!root||!gdjs.__materialController3D){s.state='WaitingForCore';s.error=root?'Material 3D controller is not loaded.':'No 3D renderer is available.';return false;}s.root=root;s.params=read(b);if(!s.contributor)s.contributor={id:'animated',order:350,requiresPhysical:function(){return false;},attach:function(m,c){attach(s,m,c);},detach:function(m,c){detach(s,m,c);}};gdjs.__materialController3D.registerContributor(root,b,s.contributor);var isCorePresent=hasCore(o,root);var coreTargets=gdjs.__materialController3D.getTargets(root);if(isCorePresent&&!coreTargets.length){s.state='WaitingForCore';s.error='';return true;}var ts=gdjs.__materialController3D.resolveBehaviorTargets?gdjs.__materialController3D.resolveBehaviorTargets(root,b):coreTargets;if(!ts.length&&!isCorePresent){s.state='WaitingForMesh';s.error='No 3D meshes found on object.';return false;}s.textures.length=0;var cs=gdjs.__materialController3D.getState(root,false);for(var i=0;i<ts.length;i++){var mat=ts[i].material;if(!isCorePresent&&gdjs.__materialController3D&&gdjs.__materialController3D.ensureIsolatedMaterial){mat=gdjs.__materialController3D.ensureIsolatedMaterial(ts[i],root);}attach(s,mat,{root:root,mesh:ts[i].mesh,slot:ts[i].slot,generation:cs?cs.generation:0});}gdjs.__materialController3D.applyAnisotropyToObject(root,s.params.anisotropicFiltering);s.appliedGeneration=cs?cs.generation:0;s.state=ts.length?'Ready':(isCorePresent?'WaitingForCore':'WaitingForMesh');s.error='';return true;}
    function tick(b,o,dt){var s=stateOf(b),root=rootOf(o),cs=root&&gdjs.__materialController3D?gdjs.__materialController3D.getState(root,false):null,g=cs?cs.generation:0;if(!root||s.state==='Uninitialized'||s.root!==root||g!==s.appliedGeneration)sync(b,o);if(s.state!=='Ready')return;var p=s.params,dirty=false;if(p.scroll){s.x=(s.x+p.speedX*dt)%1;s.y=(s.y+p.speedY*dt)%1;s.rotation=(s.rotation+p.rotSpeed*dt)%360;dirty=true;}if(p.flipbook&&s.playing&&!s.finished){var total=p.frames>0?Math.min(p.frames,p.columns*p.rows):p.columns*p.rows;s.timer+=dt;var n=Math.floor(s.timer*p.fps);if(n>0){s.timer-=n/p.fps;s.frame+=n;if(s.frame>=total){if(p.loop)s.frame%=total;else{s.frame=Math.max(0,total-1);s.finished=true;s.playing=false;}}dirty=true;}}if(s.videoTexture&&typeof s.videoTexture.update==='function')s.videoTexture.update();if(dirty)transform(s);}
    function setVideo(b,o,url,loop,muted){var s=stateOf(b);sync(b,o);if(!s.root||typeof document==='undefined')return false;if(s.video){try{s.video.pause();s.video.removeAttribute('src');s.video.load();}catch(e){}}var v=document.createElement('video');v.crossOrigin='anonymous';v.playsInline=true;v.loop=!!loop;v.muted=!!muted;v.src=String(url);var t=new THREE.VideoTexture(v);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=THREE.RepeatWrapping;t.wrapT=THREE.RepeatWrapping;var af=gdjs.__materialController3D?gdjs.__materialController3D.resolveAnisotropy(s.params.anisotropicFiltering):null;if(af!==null)t.anisotropy=af;s.video=v;s.videoTexture=t;gdjs.__materialController3D.ownResource(s.root,s,v);gdjs.__materialController3D.ownResource(s.root,s,t);var play=v.play();if(play&&play.catch)play.catch(function(e){s.error='Video playback blocked: '+e;});sync(b,o);return true;}
    function playVideo(b){var s=stateOf(b);if(!s.video)return false;var play=s.video.play();if(play&&play.catch)play.catch(function(e){s.error='Video playback blocked: '+e;});return true;}
    function pauseVideo(b){var s=stateOf(b);if(!s.video)return false;try{s.video.pause();return true;}catch(e){s.error='Video pause failed: '+e;return false;}}
    function dispose(b){var s=stateOf(b);if(s.root&&gdjs.__materialController3D){var ts=gdjs.__materialController3D.resolveBehaviorTargets?gdjs.__materialController3D.resolveBehaviorTargets(s.root,b):gdjs.__materialController3D.getTargets(s.root);for(var i=0;i<ts.length;i++)detach(s,ts[i].material,{root:s.root,mesh:ts[i].mesh,slot:ts[i].slot});gdjs.__materialController3D.unregisterContributor(s.root,b);gdjs.__materialController3D.releaseOwnedResources(s.root,s);}s.root=null;s.textures=[];s.video=null;s.videoTexture=null;s.state='Uninitialized';}
    return{read:read,stateOf:stateOf,sync:sync,tick:tick,transform:transform,setVideo:setVideo,playVideo:playVideo,pauseVideo:pauseVideo,dispose:dispose};
  })();
}
